version: '3'

services:

  database:
    image: postgres:11.5
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=freetour
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 9000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build: ../backend
    image: backend
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/freetour
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8080
      FRONTEND_URL: http://localhost:9002
    ports:
      - 9001:8080
    restart: always
    depends_on:
      - database
      - frontend
    volumes:
      - shared_images:/images

  frontend:
    build:
      context: ../frontend
      args:
        - VUE_APP_API_URL=http://localhost:9001
    image: frontend
    container_name: frontend
    ports:
      - 9002:80
    restart: always
    volumes:
      - shared_images:/images

volumes:
  pgdata:
  shared_images:
